# Generated by Django 4.2.24 on 2025-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
