# Generated by Django 4.2.24 on 2025-10-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0018_alter_media_options_remove_media_unique_hero_true_and_more'),
        ('events_app', '0002_exhibition_end_time_exhibition_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_media', to='events_app.exhibition')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='collections_app.media')),
            ],
            options={
                'unique_together': {('exhibition', 'media')},
            },
        ),
    ]
