# Generated by Django 4.2.24 on 2025-10-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_contact_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='curator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='curator_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
