# Generated by Django 4.2.24 on 2025-10-15 16:57

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='owner_app.artistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('medium', models.CharField(blank=True, max_length=200)),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('physical_available', models.BooleanField(default=False)),
                ('digital_available', models.BooleanField(default=False)),
                ('physical_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('digital_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='collections_app.collection')),
            ],
        ),
    ]
