# Generated by Django 4.2.24 on 2025-10-16 11:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name/title of the artwork', max_length=200)),
                ('medium', models.CharField(blank=True, help_text='Medium used (e.g., Oil on Canvas, Acrylic, Watercolor, Digital, Mixed Media)', max_length=200)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Width of the artwork in centimeters', max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height of the artwork in centimeters', max_digits=7, null=True)),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Depth of the artwork in centimeters (optional, for 3D works)', max_digits=7, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the artwork (in default currency)', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the artwork')),
                ('year_created', models.IntegerField(blank=True, help_text='Year the artwork was created', null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Primary image of the artwork', max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the artwork available for purchase?')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured artwork for homepage display')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when artwork was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when artwork was last updated')),
                ('artist', models.ForeignKey(help_text='The artist who created this artwork', on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='owner_app.artistprofile')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
    ]
