# Generated by Django 4.2.24 on 2025-10-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_basket_order_orderitem_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='artwork_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_art', to='collections_app.artwork'),
        ),
        migrations.AddField(
            model_name='art',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='art',
            name='depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='art',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_items', to='collections_app.art'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='collections_app.art'),
        ),
    ]
