# Generated by Django 4.2.24 on 2025-10-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0004_art_artwork_link_art_created_at_art_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='art',
            name='artwork_link',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='artwork',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='art',
            field=models.ForeignKey(blank=True, help_text='The linked Art for this basket item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_items', to='collections_app.art'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='art',
            field=models.ForeignKey(blank=True, help_text='The Art purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='collections_app.art'),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'art')},
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='artwork',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
