# Generated by Django 4.2.24 on 2025-10-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0005_alter_basketitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('original_piece', 'Original piece'), ('printed_poster', 'Printed poster'), ('digital_copy', 'Digital copy')], max_length=32)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='collections_app.art')),
            ],
            options={
                'unique_together': {('art', 'medium')},
            },
        ),
    ]
