# Generated by Django 4.2.24 on 2025-10-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0007_backfill_artvariants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected ArtVariant (format)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_items', to='collections_app.artvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'art', 'variant')},
        ),
    ]
