# Generated by Django 4.2.24 on 2025-10-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_alter_basketitem_unique_together_basketitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.IntegerField(blank=True, help_text='ArtVariant primary key at time of purchase (nullable)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_medium',
            field=models.CharField(blank=True, help_text='Human-readable medium/format of the variant at time of purchase', max_length=50),
        ),
    ]
