# Generated by Django 4.2.24 on 2025-10-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0010_phase_b_make_variant_required_and_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='variant',
            field=models.ForeignKey(help_text='Selected ArtVariant (format)', on_delete=django.db.models.deletion.PROTECT, related_name='basket_items', to='collections_app.artvariant'),
        ),
    ]
