# Generated by Django 4.2.24 on 2025-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0017_media_homepage_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveConstraint(
            model_name='media',
            name='unique_hero_true',
        ),
        migrations.RemoveConstraint(
            model_name='media',
            name='unique_second_true',
        ),
        migrations.RemoveConstraint(
            model_name='media',
            name='unique_third_true',
        ),
        migrations.RemoveField(
            model_name='media',
            name='art',
        ),
        migrations.RemoveField(
            model_name='media',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='media',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='media',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='media',
            name='variant',
        ),
        migrations.AlterField(
            model_name='media',
            name='hero',
            field=models.BooleanField(default=False, help_text='Primary hero media on homepage'),
        ),
        migrations.AlterField(
            model_name='media',
            name='second_section',
            field=models.BooleanField(default=False, help_text='Secondary homepage section'),
        ),
        migrations.AlterField(
            model_name='media',
            name='third_section',
            field=models.BooleanField(default=False, help_text='Tertiary homepage section'),
        ),
    ]
